---
- name: Load a list of individual ptfs on an ibm i system, then apply
  hosts: all
  gather_facts: false
  collections:
   - ibm.power_ibmi
  
  vars:
    to_be_loaded_ptf_list: "{{ to_be_loaded_ptf_list }}"
    loaded_list: "{{ loaded_list }}"
    temp_or_perm: "{{ temp_or_perm }}"
    delayed_option: "{{ delayed_option }}"
    auto_ipl: "{{ auto_ipl }}"

  tasks:
    - name: Include load_apply_ptfs role to Load and apply a list of single ptfs.
      include_role:
        name: load_apply_ptfs
      register: load_apply_result

    - name: Load Apply Result
      debug:
        msg: "{{ load_apply_result }}"
