---
- hosts: all
  gather_facts: false
  collections:
   - ibm.power_ibmi
  
  vars:
    save_file_path: "{{ save_file_path }}"
    lib_name: "{{ lib_name }}"

  tasks:
    - name: List /tmp directory
      local_action:
        module: ansible.builtin.find
        paths: /tmp
        recurse: no
        file_type: directory
      run_once: True
      register: directory
    
    - name: directory
      debug:
        msg: "{{ directory }}"
      
    - name: Copy a save file from awx to a remote IBM i node
      ibmi_copy:
        src: "{{ save_file_path }}"
        lib_name: "{{ lib_name }}"
      register: results

    - name: results
      debug:
        msg: "{{ results }}"
