---
- hosts: all
  gather_facts: false
  collections:
   - ibm.power_ibmi
  
  vars:
    save_file_path: "{{ save_file_path }}"
    lib_name: "{{ lib_name }}"

  tasks:
    - name: Copy a save file from awx to a remote IBM i node
      ibmi_copy:
        src: "{{ save_file_path }}"
        lib_name: "{{ lib_name }}"
      register: results

    - name: results
      debug:
        msg: "{{ results }}"
