---
- hosts: all
  gather_facts: false
  collections:
   - ibm.power_ibmi
  
  vars:
    save_file_path: "{{ save_file_path }}"
    lib_name: "{{ lib_name }}"
    host_ip: "{{ host_ip }}"
    ansible_user: "{{ ansible_user }}"

  tasks:
    - name: Copy file from localhost to awx
      fetch:
        src: "{{ save_file_path }}"
        dest: "/tmp/{{ save_file_path }}"
      delegate_to: "{{ host_ip }}"
      remote_user: "{{ ansible_user }}"

    - name: Copy a save file from awx to a remote IBM i node
      ibmi_copy:
        src: "/tmp/{{ save_file_path }}"
        lib_name: "{{ lib_name }}"
      register: results

    - name: results
      debug:
        msg: "{{ results }}"
